### ISSUE TITLE
Initial checklist for planning

### ISSUE THREAD

**Issue by rick** [rick/india#1]
![image](https://user-images.githubusercontent.com/6259/155171822-27ca7270-d211-4e73-a7ac-3a397fb7ea35.png)

My birthday is this year and we've said we're going to party in Goa. So, we're going to India, and we're also going to party in Goa.

Likely dates:

 - In-country Oct. 1 (/ Sep. 30) - Oct. 28
 - Goa: Oct. 19 - Oct. 23

**planning**

 - [x] set up slack channel #india-trip
 - [ ] book flights (JFK<->DEL)
 - [ ] ping people
 - [ ] rick.party site updates
 - [ ] get visa (30-day e-visa suffices; I will probably do 10-year multiple-entry)
 - [ ] ...

**Comment by jameswhite** [comment]
- @jameswhite
     - to India: JFK->DEL - Sep 29, 2022 / Oct 1, 2022
    - from India: DEL->JFK - Oct 29, 2022
